name: apollo-cache-updaters 
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    name: 'node ${{ matrix.node }} chrome ${{ matrix.os }} '
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 10]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run validate
  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - run: ls -asl dist
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
